### ISSUE TITLE
Question About Spurious OOD Dataset Generation for WaterBirds 

### ISSUE THREAD

**Issue by dubowsky** [deeplearning-wisc/Spurious_OOD#2]
Hi,

Thanks for your nice work in pointing out the impact of spurious effect on the OOD. I have a question about the generation of OOD dataset for WaterBirds.

The code seems that the OOD dataset is directly the Place365 dataset instead of the example shown in the figure 1 (Right), a boat in the lake. I think the shown example in the paper indicates that the Spurious OOD figure should contain an OOD object inside. Is my understanding correct? Feel free to correct me if there is any problem. Thanks!

**Comment by alvinmingsf** [comment]
Thanks for raising this issue. Yes, as also mentioned in readme, generate_placebg.py is used to generate background images. Feel free to place different OOD objects of your interest on top of background images and see how the detection performance is influenced. In our initial experiments, we tried several objects but it turns out they do out have much impact on the performance especially when the network relies on background spurious correlation during training.

**Comment by dubowsky** [comment]
Thanks for your reply and it's clear. One follow-up question is what kinds of the 'topping' objects/datasets you used in the trials? I would like to try with different 'toppings' as well.

**Comment by alvinmingsf** [comment]
Thanks for the question! By the definition of OOD, objects with labels other than the ID labels are considered valid OOD. For Waterbirds, objects like "boat", "cat" or "dogs" are all suitable toppings.

**Comment by dubowsky** [comment]
Clear. Thanks for your reply!

**Comment by yuu-Wang** [comment]
Hello author, I would like to ask politely, is the places365_standard you use a 105G large image or a 24G small image? Thank you for your reply

**Comment by yuu-Wang** [comment]
> Thanks for the question! By the definition of OOD, objects with labels other than the ID labels are considered valid OOD. For Waterbirds, objects like "boat", "cat" or "dogs" are all suitable toppings.

I want to ask if there is any code to put different OOD objects on placebg?thankyou
